[package]
name = "test-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4.39", features = ["serde"] }
async-trait = "0.1.85"
tokio-postgres = {version = "0.7.12", features = ["with-chrono-0_4"]}
tokio = "1"
dotenv="0.15"